### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by Forceu** [dillbyrne/es-cec-input#15]
When running the script I get the following error:

`Traceback (most recent call last):
  File "./es-cec-input.py", line 223, in <module>
    main()
  File "./es-cec-input.py", line 181, in main
    keylist = generate_keylist()
  File "./es-cec-input.py", line 92, in generate_keylist
    key_bindings = get_key_bindings('/opt/retropie/configs/all/retroarch.cfg')
  File "./es-cec-input.py", line 122, in get_key_bindings
    keys.append(line.split('=')[1][2:-2])
IndexError: list index out of range`

A keyboard is configured. My config file can be found at https://pastebin.com/SF4CNTDD

I am using the most current version of Retropie.

It appears that this problem occurs because I have the setting `input_player1_analog_dpad_mode" "1"` in my configuration. If I uncomment the line, the script works without any problems.

**Comment by Forceu** [comment]
I just realized that this is a problem with an invalid configuration of mine.
