### ISSUE TITLE
Errors on line 209 (press_keys(lines.next(), device, keylist))

### ISSUE THREAD

**Issue by NSF12345** [dillbyrne/es-cec-input#17]
Issue in the title

Setup is a little different to most;
RasPi3B+ running OSMC with menu options to launch RetroPi
Retropi was installed using the "retrosmc" script (which works fine)

Followed the instructions to enable CEC in es (replacing "pi" with "osmc" in `sudo adduser pi uinput` - I gave the script a once over to make sure that the user "pi" wasn't specifically referenced) but when I run es-cec-input.py
```
osmc@osmc_main:~$ ./es-cec-input.py
Traceback (most recent call last):
  File "./es-cec-input.py", line 224, in <module>
    main()
  File "./es-cec-input.py", line 209, in main
    press_keys(lines.next(), device, keylist)
StopIteration
```

Additionally once this occurs, vi fails with
`vi: can't read user input`
but I'm assuming that's because of the errors above - a reboot sorts it

Not really troubleshooted as I haven't a clue where to start. I did have issues installing python-uinput as I needed to install wheel first.

Any thoughts?

**Comment by googanhiem** [comment]
I also had issues installing python-uinput on a osmc system, which is probably why we can't get this to work. Even with installing pip and other dependencies it still gave a couple errors. 

I get the same error when running the script.
