### ISSUE TITLE
Don't work on RetroPie 4.6

### ISSUE THREAD

**Issue by hollysheep** [dillbyrne/es-cec-input#26]
Should the script work with retropie 4.6? There is an error when i start the script

```
Traceback (most recent call last):
  File "./es-cec-input.py", line 224, in <module>
    main()
  File "./es-cec-input.py", line 183, in main
    device = register_device(keylist)
  File "./es-cec-input.py", line 129, in register_device
    return uinput.Device(keylist)
  File "/usr/lib/python2.7/dist-packages/uinput/__init__.py", line 178, in __init__
    self.__uinput_fd = fd or fdopen()
  File "/usr/lib/python2.7/dist-packages/uinput/__init__.py", line 84, in fdopen
    return _libsuinput.suinput_open()
  File "/usr/lib/python2.7/dist-packages/uinput/__init__.py", line 70, in _open_error_handler
    raise OSError(code, msg)
OSError: [Errno 13] Failed to open the uinput device: Permission denied
```

It works when i start it with sudo but cec doesn't work.

**Comment by allenbina** [comment]
I think the permissions issue can be fixed by adding your user to uinput group.  I copied this from the readme.  This assumes you are using the pi username.

```
Run the code as a non root user

You must first create the uinput group

sudo addgroup uinput

Then add the pi user to the uinput group

sudo adduser pi uinput
```

**Comment by evbernardes** [comment]
Having the same problem, Raspi 3B+ with the latest retropie. Created the group and added pi to it, still have the same problem

**Comment by Markisen** [comment]
I found the solution here: https://github.com/tuomasjjrasanen/python-uinput/issues/6#issuecomment-538710069
I also needed to do the following:

Change group ownership and permissions on /dev/uinput:

sudo chmod g+rw /dev/uinput
sudo chgrp uinput /dev/uinput

**Comment by Kenarude** [comment]
Hello,
I'm not an expert on linux but by using what was said in this thread and made some search, I would like to share my 2 cents knowledge.
I think there was some changes in the way the access right are assigned to /dev/uinput. I figured out how to make it working as it was previously. 
First, as I fell into the trap I give a clue :), the udev rules are in 3 lines and not on one line only (the magic of copy/paste)
So I added GROUP to the uinput device otherwise it is assigned to the root.
<pre><code>ACTION=="add|change", KERNEL=="event[0-9]*", ENV{ID_VENDOR_ID}=="012a", ENV{ID_MODEL_ID}=="034b", ENV{ID_INPUT_KEYBOARD}="1", ENV{ID_INPUT_TABLET}="1"
SUBSYSTEM=="input", ATTRS{name}=="python-uinput", ENV{ID_INPUT_KEYBOARD}="1"
KERNEL=="uinput", GROUP="uinput", MODE:="0660"</code></pre>

What can be done also is instead of using a crontab rule to start the script we can use a user systemd service.
Create the folder ~/.config/systemd/user if it doesn't exist.
Create a file named for example cec.service into that folder.
add the following information (take care to set correctly the path to your script)

<pre><code>[Unit]
Description=CEC to keyboard input converter

[Service]
ExecStart=python /path/to/the/script/es-cec-input.py

[Install]
WantedBy=default.target</code></pre>

When done, enable the service
<pre><code>systemctl --user enable cec.service</code></pre>

Now you can reboot and test if it works.

I think this could also be done with a systemd system service so as not to change the uinput group but I haven't tried it yet.
